// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUx1hPe3XS1i27kmui7bjKx65mevHP4Vw',
    appId: '1:432631275949:android:421796573a67e04e888124',
    messagingSenderId: '432631275949',
    projectId: 'smartcollar-c69c1',
    storageBucket: 'smartcollar-c69c1.firebasestorage.app',
    databaseURL:
        'https://smartcollar-c69c1-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS5rY9aVHXNbqMx1sgEuT5nNJii8FVVJs',
    appId: '1:432631275949:ios:4a73cae001034306888124',
    messagingSenderId: '432631275949',
    projectId: 'smartcollar-c69c1',
    storageBucket: 'smartcollar-c69c1.firebasestorage.app',
    iosBundleId: 'com.example.smartcollarMobileapp',
    databaseURL:
        'https://smartcollar-c69c1-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Qw6wTf-iIxPaMusi8Nz04RhmoMAv6Y4',
    appId: '1:432631275949:web:799f136049650531888124',
    messagingSenderId: '432631275949',
    projectId: 'smartcollar-c69c1',
    authDomain: 'smartcollar-c69c1.firebaseapp.com',
    storageBucket: 'smartcollar-c69c1.firebasestorage.app',
    measurementId: 'G-B0JKVL86VM',
    databaseURL:
        'https://smartcollar-c69c1-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
